listings/urls.py
from django.urls import path, include
from . import views
from .views import PropertyViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'properties', PropertyViewSet)

urlpatterns = [
    path('', views.home, name='home'),
    path('property_list/', views.property_list, name='property_list'),
    path('tenant-profile/', views.tenant_profile, name='tenant_profile'),  # Профиль арендатора
    path('landlord-profile/', views.landlord_profile, name='landlord_profile'),  # Профиль арендодателя
    path('search/', views.property_search, name='property_search'),
    path('contacts/', views.contacts, name='contacts'),
    path('properties/', views.property_list, name='property_list'),

    path('properties/', views.property_list, name='property_list'),
    path('create/', views.create_property, name='create_property'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('api/', include(router.urls)),
]

rent_easy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/models.py
from django.db import models
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords


class Property(models.Model):

    title = models.CharField("Название", max_length=100)
    city = models.ForeignKey('City', on_delete=models.CASCADE, related_name='cities')
    # city = models.CharField("Город", max_length=255, default="Moscow", choices=PROPERTY_CITY_CHOICES)
    district = models.TextField("Район", max_length=255, default=False)
    property_type = models.ForeignKey("PropertyType", on_delete=models.CASCADE, related_name='property_type', verbose_name="Тип жилья", default=0, null=False)
    description = models.TextField("Описание")
    room_count = models.IntegerField("Количество комнат", default=1)
    price = models.DecimalField("Цена", max_digits=10, decimal_places=2)
    balcony = models.BooleanField("Балкон", default=False)
    parking = models.BooleanField("Парковка", default=False)
    wifi = models.BooleanField("Wi-Fi", default=False)
    landlord = models.ForeignKey('Landlord', on_delete=models.CASCADE, related_name='properties', verbose_name="Арендодатель", default=0)
    image = models.ImageField(upload_to='properties/', blank=True, null=True)

    history = HistoricalRecords()
    
    def __str__(self):
        return f"{self.title}"

class PropertyType(models.Model):
    name = models.CharField("Тип жилья", max_length=50)

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField("Страна",  max_length=100)

    def __str__(self):
        return self.name
    
class City(models.Model):
    name = models.CharField("Город", max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='cities')

    def __str__(self):
        return f"{self.name} {self.country.name}"

class Landlord(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15)

    history = HistoricalRecords()

    def __str__(self):
        return self.name
    # любые другие поля

    def __str__(self):
        return self.name

class Tenant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # дополнительные поля для арендатора, если есть

    def __str__(self):
        return self.user.username
    
class property_list(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    location = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class TenantProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.user.username

class LandlordProfile(models.Model):
    name = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100, blank=True)
    license_number = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.company_name

listings/forms.py
# listings/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Property, Country, City, PropertyType

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class PropertySearchForm(forms.Form):
    country = forms.ModelChoiceField(
        queryset=Country.objects.all(),
        required=False,
        label="Страна"
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.none(),
        required=False,
        label="Город"
    )

    # При создании формы — динамически обновляем queryset для поля city
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Используем данные из POST/GET
        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # некорректный ввод — оставим пустой queryset
        elif self.initial.get('country'):
            # Если у формы передан initial (например, для редактирования)
            country_id = self.initial.get('country').id
            self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')

    district = forms.CharField(required=False, label="Район")
    property_type = forms.ModelChoiceField(
        queryset = PropertyType.objects.all(),  # Все типы жилья из модели PropertyType
        required = False,
        label="Тип жилья"
    )
    room_count = forms.IntegerField(required=False, min_value=1, label="Количество комнат")
    price_min = forms.DecimalField(required=False, min_value=0, decimal_places=2, label="Минимальная цена")
    price_max = forms.DecimalField(required=False, min_value=0, decimal_places=2, label="Максимальная цена")
    
    balcony = forms.BooleanField(required=False, label="Балкон")
    parking = forms.BooleanField(required=False, label="Парковка")
    wifi = forms.BooleanField(required=False, label="Wi-Fi")

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['title', 'description', 'city', 'district', 'property_type', 'room_count', 'price', 'balcony', 'parking', 'wifi', 'landlord', 'image']

listings/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .models import Property, Landlord, TenantProfile, LandlordProfile, City
from .forms import PropertySearchForm, PropertyForm
from django.core.paginator import Paginator
from .serializers import PropertySerializer, LandlordSerializer
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.decorators import action
from django_filters.rest_framework import DjangoFilterBackend
from django.db.models import Q



def property_list(request):
    properties = Property.objects.all()
    print(f"Объекты недвижимости: {properties.count()}")  # Добавьте вывод количества объектов

    paginator = Paginator(properties, 5)
    page_number = request.GET.get('page')
    print(f"Номер страницы: {page_number}")  # Отладочный вывод

    page_obj = paginator.get_page(page_number)

    return render(request, 'listings/property_list.html', {'page_obj': page_obj})



def home(request):
    properties = Property.objects.all()[:5]  # Примеры жилья
    return render(request, 'listings/home.html', {'properties': properties})

def search(request):    
    # Логика поиска
    return render(request, 'listings/search.html')

def listing_detail(request, pk):
    property = get_object_or_404(Property, pk=pk)
    return render(request, 'listings/listing_detail.html', {'property': property})


def contacts(request):
    return render(request, 'listings/contact.html')



def tenant_profile(request):
    tenant_profile = TenantProfile.objects.first()  # Получение первого профиля арендатора
    return render(request, 'listings/tenant_profile.html', {'profile': tenant_profile})

def landlord_profile(request):
    landlord_profile = LandlordProfile.objects.first()  # Получение первого профиля арендодателя
    return render(request, 'listings/landlord_profile.html', {'profile': landlord_profile})


def property_search(request):
    properties = Property.objects.all()  # Получаем все объекты

    # Логика фильтрации (если нужна)
    if request.method == 'GET':
        form = PropertySearchForm(request.GET or None)

        if form.is_valid():
            city = form.cleaned_data.get('city')
            district = form.cleaned_data.get('district')
            property_type = form.cleaned_data.get('property_type')
            room_count = form.cleaned_data.get('room_count')
            price_min = form.cleaned_data.get('price_min')
            price_max = form.cleaned_data.get('price_max')
            balcony = form.cleaned_data.get('balcony')
            parking = form.cleaned_data.get('parking')
            wifi = form.cleaned_data.get('wifi')

            if city:
                properties = properties.filter(city=city)
            if district:
                properties = properties.filter(district__icontains=district)
            if property_type:
                properties = properties.filter(property_type=property_type)
            if room_count:
                properties = properties.filter(room_count=room_count)
            if price_min is not None:
                properties = properties.filter(price__gte=price_min)
            if price_max is not None:
                properties = properties.filter(price__lte=price_max)
            if balcony:
                properties = properties.filter(balcony=True)
            if parking:
                properties = properties.filter(parking=True)
            if wifi:
                properties = properties.filter(wifi=True)

    else:
        form = PropertySearchForm()

    # Пагинация
    paginator = Paginator(properties, 5)  # 5 объектов на странице
    page_number = request.GET.get('page')  # Получаем номер страницы из запроса
    page_obj = paginator.get_page(page_number)  # Получаем объект страницы

    return render(request, 'listings/property_search.html', {'form': form, 'page_obj': page_obj})

def create_property(request):
    if request.method == 'POST':
        form = PropertyForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')  # Перенаправление после успешного сохранения
    else:
        form = PropertyForm()
    return render(request, 'listings/create_property.html', {'form': form})

def load_cities(request):
    country_id = request.GET.get('country_id')  # Получаем ID страны из запроса
    cities = City.objects.filter(country_id=country_id).order_by('name')  # Фильтруем города
    city_list = [{'id': city.id, 'name': city.name} for city in cities]  # Подготавливаем данные
    return JsonResponse({'cities': city_list})  # Возвращаем данные в формате JSON

# REST

class PropertyViewSet(viewsets.ModelViewSet):
    queryset = Property.objects.all()
    serializer_class = PropertySerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['city', 'property_type', 'balcony', 'wifi', 'parking']

    @action(methods=['GET'], detail=False)
    def get_property_list(self, request):
        queryset = Property.objects.all()
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = PropertySerializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        serializer = PropertySerializer(queryset, many=True)
        return Response(serializer.data)
    
    @action(methods=['GET'], detail=False)
    
    def with_some_feature(self, request):
        # """
        # Возвращает все объекты, у которых есть хотя бы один из признаков:
        # - балкон
        # - Wi-Fi
        # - парковка
        # """
        queryset = Property.objects.filter(
            Q(balcony=True) | Q(wifi=True) | Q(parking=True)
        )
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    @action(methods=['POST'], detail=True)
    def update_property_info(self, request, pk=None):

        property_instance = self.get_object()
        
        new_price = request.data.get('price')
        if new_price:
            property_instance.price = new_price
            property_instance.save()
            return Response({"status": "Price updated successfully"})
        else:
            return Response({"status": "No price provided"}, status=400)
        
        # new_title = request.data.get('title')
        # if new_title:
        #     property_instance.title = new_title
        #     property_instance.save()
        #     return Response({"status": "Title updated successfully"})
        # else:
        #     return Response({"status": "No title provided"}, status=400)
        

class LandlordViewSet(viewsets.ModelViewSet):
    queryset = Landlord.objects.all()
    serializer_class = LandlordSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['name', 'email', 'phone']

    @action(methods=['GET'], detail=False)
    def get_property_list(self, request):
        queryset = Landlord.objects.all()
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = LandlordSerializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        serializer = LandlordSerializer(queryset, many=True)
        return Response(serializer.data)

    @action(methods=['POST'], detail=True)
    def update_landlord_info(self, request, pk=None):

        landlord_instance = self.get_object()
        
        new_name = request.data.get('name')
        if new_name:
            landlord_instance.name = new_name
            landlord_instance.save()
            return Response({"status": "Name updated successfully"})
        else:
            return Response({"status": "No name provided"}, status=400)

listings/templates/listings/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}RentEasy{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

listings/templates/listings/contact.html
{% load static %} <!-- Загрузка статического тега -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Подключение ваших стилей -->
</head>
<body>
    <a href="{% url 'home' %}">Главная</a>
    <header>
        <h1>Добро пожаловать в Rent Easy!</h1>
        <nav>
            <ul>
                <li><a href="{% url 'property_list' %}">Жильё</a></li>
                <li><a href="{% url 'tenant_profile' %}">Профиль арендатора</a></li> <!-- Ссылка на профиль арендатора -->
                <li><a href="{% url 'landlord_profile' %}">Профиль арендодателя</a></li> <!-- Ссылка на профиль арендодателя -->
                <li><a href="{% url 'contacts' %}">Контакты</a></li> <!-- Ссылка на контакты -->
                <li><a href="{% url 'property_search' %}">Поиск</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <h2>Контакты</h2>
        <p>Если у вас есть вопросы, пожалуйста, свяжитесь с нами:</p>

        <form method="POST" action="{% url 'contacts' %}">
            {% csrf_token %}
            <label for="name">Имя:</label>
            <input type="text" name="name" id="name" required>

            <label for="email">Email:</label>
            <input type="email" name="email" id="email" required>

            <label for="message">Сообщение:</label>
            <textarea name="message" id="message" required></textarea>

            <button type="submit">Отправить</button>
        </form>

        <h3>Часто задаваемые вопросы (FAQ)</h3>
        <ul>
            <li><strong>Как мне забронировать жилье?</strong> Просто заполните форму на странице поиска и выберите понравившийся объект.</li>
            <li><strong>Какие условия аренды?</strong> Условия могут различаться в зависимости от арендодателя. Пожалуйста, читайте информацию на странице конкретного жилья.</li>
        </ul>
</main>

listings/templates/listings/create_property.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить недвижимость</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Подключите свой CSS, если нужно -->
</head>
<body>
    <a href="{% url 'home' %}">Главная</a>
    <header>
        <h1>Добро пожаловать в Rent Easy!</h1>
        <nav>
            <ul>
                <li><a href="{% url 'property_list' %}">Жильё</a></li>
                <li><a href="{% url 'tenant_profile' %}">Профиль арендатора</a></li> <!-- Ссылка на профиль арендатора -->
                <li><a href="{% url 'landlord_profile' %}">Профиль арендодателя</a></li> <!-- Ссылка на профиль арендодателя -->
                <li><a href="{% url 'contacts' %}">Контакты</a></li> <!-- Ссылка на контакты -->
                <li><a href="{% url 'property_search' %}">Поиск</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <div class="container">
            <h1>Добавить недвижимость</h1>
            {% if form %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Добавить жилье</button>
            </form>
            {% else %}
                <p>Форма не передана в шаблон.</p>
            {% endif %}

            <a href="{% url 'property_list' %}">Назад к списку недвижимости</a> <!-- Ссылка для возврата к списку -->
        </div>
    </main>
</body>
</html>

listings/templates/listings/home.html
<!-- rent_easy/listings/templates/listings/home.html -->
{% load static %} <!-- Загрузка статического тега -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Подключение ваших стилей -->
</head>
<body>
    <a href="{% url 'create_property' %}">Создание</a>
    <header>
        <h1>Добро пожаловать в Rent Easy!</h1>
        <nav>
            <ul>
                <li><a href="{% url 'property_list' %}">Жильё</a></li>
                <li><a href="{% url 'tenant_profile' %}">Профиль арендатора</a></li> <!-- Ссылка на профиль арендатора -->
                <li><a href="{% url 'landlord_profile' %}">Профиль арендодателя</a></li> <!-- Ссылка на профиль арендодателя -->
                <li><a href="{% url 'contacts' %}">Контакты</a></li> <!-- Ссылка на контакты -->
                <li><a href="{% url 'property_search' %}">Поиск</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <h2>О нас</h2>
        <h3>Добро пожаловать на RentEasy – ваш надежный помощник в поиске жилья!</h3>
        <p>Мы понимаем, что поиск идеального места для жизни может быть сложной задачей. Поэтому мы создали платформу, которая упрощает этот процесс и делает его более эффективным. На [Название сайта] вы можете найти:</p></p>
        <ul>
            <li><p>Широкий выбор объектов недвижимости: от уютных студий и современных квартир до просторных домов. Мы предлагаем различные варианты, чтобы удовлетворить ваши потребности и бюджет.</p></li>
            <li><p>Интуитивно понятный интерфейс: наш сайт разработан с учетом удобства пользователя. Легко настраиваемые фильтры помогут вам быстро найти жилье по местоположению, цене, размеру и другим критериям.</p></li>
            <li><p>Актуальные объявления: мы обновляем наш каталог ежедневно, чтобы предоставить вам самые свежие предложения. С нами вы всегда будете в курсе последних новинок на рынке недвижимости.</p></li>
            <li><p>Информация о районах: каждый объект недвижимости сопровождается подробной информацией о районе: инфраструктура, транспортная доступность, школы и магазины. Мы хотим, чтобы вы чувствовали себя уверенно в своем выборе.</li>
            <li><p>Поддержка 24/7: наша команда готова помочь вам в любое время. У вас есть вопрос или нужна помощь в поиске? Свяжитесь с нами, и мы с радостью ответим на все ваши вопросы.</p></li>
        </ul>
        <p>На [Название сайта] мы стремимся сделать поиск жилья простым и приятным. Начните свое путешествие к новому дому уже сегодня!</p>
    </main>
    <footer>
        <p>&copy; 2024 Rent Easy. Все права защищены.</p>
    </footer>
</body>
</html>

listings/templates/listings/landlord_profile.html
<!-- rent_easy/listings/templates/listings/landlord_profile.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль Арендодателя</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <h1>Профиль Арендодателя</h1>
    </header>
    <main>
        <h2>{{ profile.user.username }}</h2>
        <p>Название компании: {{ profile.company_name }}</p>
        <p>Номер лицензии: {{ profile.license_number }}</p>
    </main>
    <footer>
        <p>&copy; 2024 Rent Easy. Все права защищены.</p>
    </footer>
</body>
</html>

listings/templates/listings/listing_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль Арендодателя</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <h1>Добро пожаловать в Rent Easy!</h1>
        <nav>
            <ul>
                <li><a href="{% url 'property_list' %}">Жильё</a></li>
                <li><a href="{% url 'tenant_profile' %}">Профиль арендатора</a></li> <!-- Ссылка на профиль арендатора -->
                <li><a href="{% url 'landlord_profile' %}">Профиль арендодателя</a></li> <!-- Ссылка на профиль арендодателя -->
                <li><a href="{% url 'contacts' %}">Контакты</a></li> <!-- Ссылка на контакты -->
                <li><a href="{% url 'property_search' %}">Поиск</a></li>
            </ul>
        </nav>
    </header>
    <h2>{{ property.title }}</h2>
    <p><strong>Описание:</strong> {{ property.description }}</p>
    <p><strong>Город:</strong> {{ property.city }}</p>
    <p><strong>Район:</strong> {{ property.district }}</p>
    <p><strong>Тип жилья:</strong> {{ property.property_type }}</p>
    <p><strong>Количество комнат:</strong> {{ property.num_rooms }}</p>
    <p><strong>Цена:</strong> {{ property.price }} руб./мес.</p>
    <p><strong>Дополнительные характеристики:</strong></p>
    <ul>
        <li>Балкон: {{ property.balcony|yesno:"Да,Нет" }}</li>
        <li>Парковка: {{ property.parking|yesno:"Да,Нет" }}</li>
        <li>Мебель: {{ property.furniture|yesno:"Да,Нет" }}</li>
        <li>Животные: {{ property.pets_allowed|yesno:"Да,Нет" }}</li>
        <li>Wi-Fi: {{ property.wifi|yesno:"Да,Нет" }}</li>
    </ul>

    <a href="mailto:{{ property.owner.email }}">Связаться с арендодателем</a>

    <button type="button" onclick="addToFavorites({{ property.id }})">Добавить в избранное</button>

    <script>
    function addToFavorites(propertyId) {
        // Логика добавления в избранное
        alert('Объект ' + propertyId + ' добавлен в избранное!');
    }
    </script>
</body>

listings/templates/listings/property_search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль Арендодателя</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <a href="{% url 'home' %}">Главная</a>
    <header>
        <h2>Поиск жилья</h2>
    </header>
    <main>
        <!-- listings/templates/listings/property_search.html -->
        <h1>Поиск недвижимости</h1>

        <form method="get" action="">
            <!-- Форма для фильтрации (как была) -->
            {{ form.as_p }}
            <button type="submit">Поиск</button>
        </form>
        
        <!-- Список недвижимости -->
        <div class="property_search">
            {% for property in page_obj %}
                <div class="property_list" style="font-size: 1.5rem;">
                    {% if property.image %}
                        <img class="property_img" src="{{ property.image.url }}" alt="{{ property.title }}" width="30%"/>
                    {% endif %}
                    <div class="property_text">
                        <h3>{{ property.title }}</h3>
                        <p>{{ property.description }}</p>
                        <p>Цена: {{ property.price }} руб.</p>
                        <p>Город: {{ property.city.name }}</p>
                    </div>
                </div>
            {% empty %}
                <p>Нет объектов, соответствующих критериям поиска.</p>
            {% endfor %}
        </div>
        
        <!-- Пагинация -->
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; Первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}
        
                <span class="current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
                {% endif %}
            </span>
        
            <!-- Кнопки для перехода к страницам -->
            <div class="page-links">
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <span class="current-page">{{ i }}</span>
                    {% else %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_country').change(function () {
                const countryId = $(this).val();  // Получаем выбранную страну
                if (countryId) {
                    $.ajax({
                        url: '/ajax/load-cities/',  // URL из urls.py
                        data: {
                            country_id: countryId  // Передаем ID страны
                        },
                        success: function (data) {
                            const citySelect = $('#id_city');
                            citySelect.empty();  // Очищаем старые данные
                            citySelect.append('<option value="">---------</option>');  // Добавляем пустую опцию
                            data.cities.forEach(function (city) {
                                citySelect.append(new Option(city.name, city.id));  // Добавляем новые опции
                            });
                        }
                    });
                } else {
                    $('#id_city').empty();  // Если страна не выбрана, очищаем список городов
                }
            });
        });
    </script>
</body>

listings/templates/listings/test_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Отдельные поля формы</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div>
                <label>{{ field.label_tag }}</label>
                {{ field }}
                {% if field.errors %}
                    <p style="color: red;">{{ field.errors }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit">Добавить жилье</button>
    </form>
</body>
</html>